# Generated by Django 4.1.1 on 2022-10-28 15:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_slug_bookimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimage',
            name='alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
