# Generated by Django 4.1.1 on 2022-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_options_book_created_book_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
